# Generated by Django 3.1.6 on 2024-08-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('businessDetailId', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(blank=True, max_length=200, null=True)),
                ('businessRegistrationNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('natureOfBusiness', models.CharField(blank=True, max_length=200, null=True)),
                ('streetAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('postalAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('alternatePhoneNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=0)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
