# Generated by Django 3.1.6 on 2024-08-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0003_auto_20240813_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
