# Generated by Django 3.1.6 on 2024-08-21 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0004_auto_20240813_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='certOfCorporation',
            field=models.FileField(blank=True, null=True, upload_to='static/cert-of-corporation/'),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='commenceBusinessCert',
            field=models.FileField(blank=True, null=True, upload_to='static/commence-business-certs/'),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='companyProfileCert',
            field=models.FileField(blank=True, null=True, upload_to='static/company-profile-certs/'),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='numberOfDirectors',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DirectorIds',
            fields=[
                ('directorIdsId', models.AutoField(primary_key=True, serialize=False)),
                ('directorIds', models.FileField(blank=True, null=True, upload_to='static/directors-certs/')),
                ('businessDetailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_id_business', to='onboard.businessdetails')),
            ],
        ),
    ]
