# Generated by Django 3.1.6 on 2024-08-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0006_auto_20240825_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='officialPhoneNumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
